# Generated by Django 2.2.7 on 2019-11-09 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_no', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('student_name', models.CharField(blank=True, max_length=41, null=True)),
                ('father_name', models.CharField(blank=True, max_length=41, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=40, null=True)),
                ('contact_number', models.CharField(max_length=30)),
                ('class_std', models.CharField(choices=[('LKG', 'LKG'), ('UKG', 'UKG'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('NC', 'NC'), ('PNC', 'PNC'), ('NR', 'NR')], max_length=10)),
                ('category', models.CharField(choices=[('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('GENERAL', 'GENERAL')], max_length=10)),
                ('blood_group', models.CharField(choices=[('A', 'A'), ('A+', 'A+'), ('B', 'B'), ('B+', 'B+'), ('AB+', 'AB+'), ('O+', 'O+'), ('O-', 'O-')], max_length=10)),
                ('conveyance', models.BooleanField()),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TutionAdmissionFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default='1', max_length=9)),
                ('tution_fee', models.IntegerField(verbose_name='Tution Fee')),
                ('admission_fee', models.IntegerField(verbose_name='Admission Fee')),
                ('conveyance_fee', models.IntegerField(verbose_name='IntegerField')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Student')),
            ],
        ),
    ]
